# Generated by Django 3.1.3 on 2020-11-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nametype', models.CharField(blank=True, max_length=10, null=True)),
                ('recclass', models.CharField(blank=True, max_length=30, null=True)),
                ('mass', models.FloatField(blank=True, max_length=10, null=True)),
                ('fall', models.CharField(blank=True, max_length=6, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('reclat', models.FloatField(blank=True, null=True)),
                ('reclong', models.FloatField(blank=True, null=True)),
                ('GeoLocation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
