# Generated by Django 3.1.3 on 2020-11-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteorite',
            old_name='GeoLocation',
            new_name='geoLocation',
        ),
    ]
